################
version: '3.9' #
services:      #
################
#
######################################################
 Adminer:
  image: 'adminer'
  container_name: 'adminer'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'adminer'
  external_links:
   - 'mariadb:mariadb'
   - 'mysql:mysql'
  environment:
   ADMINER_DEFAULT_SERVER: ''
  ports:
   - '644:8080'
  labels:
   Cacher: 'Non'
######################################################
 Dozzle:
  image: 'amir20/dozzle'
  container_name: 'dozzle'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'dozzle'
  volumes:
   - '/var/run/docker.sock:/var/run/docker.sock'
  ports:
   - '1005:8080'
  labels:
   Cacher: 'Non'
######################################################
