version: '3.9'
services:
###############################################
 Emby:
  image: 'emby/embyserver'
  container_name: 'emby'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'emby'
  environment:
   UID:  '1000'
   GUID: '1000'
   GIDLIST: '100'
  volumes:
   - 'Emby:/config'
   - 'DOWNLOAD:/media/Download:rw'
   - 'MUSIC:/media/Music:ro'
   - 'VIDEO:/media/Video:ro'
  ports:
   - '8096:8096' # HTTP
###############################################
 Jellyfin:
  image: 'linuxserver/jellyfin'
  container_name: 'jellyfin'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'jellyfin'
  environment:
   JELLYFIN_PublishedServerUrl: '0.0.0.0'
   TS: 'Europe/Paris'
   PUID: '1000'
   PGID: '1000'
  volumes:
   - 'Jellyfin:/config'
   - 'DOWNLOAD:/media/Download:rw'
   - 'MUSIC:/media/Music:ro'
   - 'VIDEO:/media/Video:ro'
  ports:
   - '8097:8096'
  labels:
   Cacher: 'Non'
###############################################
volumes:
 Emby:
  external: false

 Jellyfin:
  external: false

 DOWNLOAD:
  external: true

 MUSIC:
  external: true

 VIDEO:
  external: true
###############################################
