################
version: '3.9' #
services:      #
################
#
###################################################################
 adguardhome:
  image: 'adguard/adguardhome'
  container_name: 'adguardhome'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'adguardhome'
  environment:
   TZ: 'Europe/Paris'
  volumes:
   - '/etc/localtime:/etc/localtime:ro'
   - 'adguardhome_conf:/opt/adguardhome/conf'
   - 'adguardhome_work:/opt/adguardhome/work'
  ports:
   - '3000:3000' # Installation
   - '53:53/udp' # DNS
   - '53:53/tcp' # DNS
   - '3272:80'   # WebUI
   
  labels:
   Cacher: 'Non'
###################################################################
# DATABASE: bitwarden | USER: bitwarden | PASS: bitwarden
 bitwarden:
  image: 'vaultwarden/server'
  container_name: 'bitwarden'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'bitwarden'
  external_links:
   - 'mariadb:db'
  environment:
   TZ: 'Europe/Paris'
   DOMAIN: 'http://db'
   DATA_FOLDER: 'data'
   ADMIN_TOKEN: 'admin'
   DATABASE_URL: 'mysql://bitwarden:bitwarden@db:3306/bitwarden'
  volumes:
    - 'bitwarden:/data'
  ports:
   - '7777:80'
   - '3012:3012'
  labels:
   Cacher: 'Non'
######################################################
 NginxProxyManager:
  image: 'jc21/nginx-proxy-manager'
  container_name: 'nginx'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'nginxproxymanager'
  external_links:
   - 'mariadb:db'
  environment:
   TZ: 'EUROPE\PARIS'
   DB_MYSQL_HOST: 'db'
   DB_MYSQL_PORT: '3306'
   DB_MYSQL_NAME: 'nginx'
   DB_MYSQL_USER: 'nginx'
   DB_MYSQL_PASSWORD: 'nginx'
  volumes:
   - 'nginx_config:/config'
   - 'nginx_certif:/etc/letsencrypt'
   - 'nginx_data:/data'
  ports:
   - '80:80'
   - '81:81'
   - '443:443'
  labels:
   Cacher: 'Non'
###################################################################
volumes:
 adguardhome_conf:
  external: false

 adguardhome_work:
  external: false

 bitwarden:
  external: false

 nginx_config:
  external: false

 nginx_certif:
  external: false

 nginx_data:
  external: false
###################################################################
