################
version: '3.9' #
services:      #
################
#
######################################################
 Adminer:
  image: 'adminer'
  container_name: 'adminer'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'adminer'
  external_links:
   - 'mariadb:db'
  environment:
   ADMINER_DEFAULT_SERVER: 'db'
  ports:
   - '644:8080'
  labels:
   Cacher: 'Non'
######################################################
 Dozzle:
  image: 'amir20/dozzle'
  container_name: 'dozzle'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'dozzle'
  volumes:
   - '/var/run/docker.sock:/var/run/docker.sock'
  ports:
   - '1005:8080'
  labels:
   Cacher: 'Non'
######################################################
 NginxProxyManager:
  image: 'jc21/nginx-proxy-manager'
  container_name: 'nginx'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'nginxproxymanager'
  external_links:
   - 'mariadb:db'
  environment:
   TZ: 'EUROPE\PARIS'
   DB_MYSQL_HOST: 'db'
   DB_MYSQL_PORT: '3306'
   DB_MYSQL_NAME: 'nginx'
   DB_MYSQL_USER: 'nginx'
   DB_MYSQL_PASSWORD: 'nginx'
  volumes:
   - 'nginx_config:/config'
   - 'nginx_certif:/etc/letsencrypt'
   - 'nginx_data:/data'
  ports:
   - '80:80'
   - '81:81'
   - '443:443'
  labels:
   Cacher: 'Non'
######################################################
volumes:
 nginx_config:
  external: false
 nginx_certif:
  external: false
 nginx_data:
  external: false
######################################################
