################
version: '3.9' #
services:      #
################
#
################################################
 Flaresolverr:
  image: 'ghcr.io/flaresolverr/flaresolverr'
  container_name: 'flaresolverr'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'flaresolverr'
  environment:
   LOG_LEVEL: 'info'
   LOG_HTML: 'false'
   CAPTCHA_SOLVER: 'none'
  ports:
   - '1115:8191'
  labels:
   Cacher: 'oui'
################################################
 XXXX:
  image: ''
  container_name: ''
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: ''
  environment:
  volumes:
   - ''
  ports:
   - ''
  labels:
   Cacher: 'oui'
################################################
 KMS:
  image: 'mikolatero/vlmcsd'
  container_name: 'kms'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'kms'
  ports:
   - '1688:1688'
  labels:
   Cacher: 'oui'
################################################
volumes:
 XXXX:
  external: false
