################
version: '3.9' #
services:      #
################
#
################################################
 Flaresolverr:
  image: 'ghcr.io/flaresolverr/flaresolverr'
  container_name: 'flaresolverr'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'flaresolverr'
  environment:
   LOG_LEVEL: 'info'
   LOG_HTML: 'false'
   CAPTCHA_SOLVER: 'none'
  ports:
   - '1115:8191'
  labels:
   Cacher: 'Oui'
################################################
 Jackett:
  image: 'linuxserver/jackett'
  container_name: 'jackett'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'jackett'
  sysctls:
   - net.ipv6.conf.all.disable_ipv6=1
  dns:
   - 192.168.0.1
   - 8.8.8.8
  environment:
   AUTO_UPDATE: 'true'
   TZ: 'EUROPE\PARIS'
   PUID: '0'
   PGID: '0'
  volumes:
   - 'Jackett:/config'
  ports:
   - '1111:9117'
  labels:
   Cacher: 'Oui'
################################################
 XXXX:
  image: ''
  container_name: ''
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: ''
  environment:
  volumes:
   - ''
  ports:
   - ''
  labels:
   Cacher: 'Oui'
################################################
 KMS:
  image: 'mikolatero/vlmcsd'
  container_name: 'kms'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'kms'
  ports:
   - '1688:1688'
  labels:
   Cacher: 'Oui'
################################################
volumes:
 Jackett:
  external: false
